{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-notesbase
  labels:
    {{- include "notesbase.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "notesbase.databaseURL" . | quote }}
  JWT_SECRET: {{ required "config.jwtSecret is required" .Values.config.jwtSecret | quote }}
  MINIO_ACCESS_KEY: {{ include "notesbase.minioAccessKey" . | quote }}
  MINIO_SECRET_KEY: {{ include "notesbase.minioSecretKey" . | quote }}
{{- end }}
