apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-notesbase
  labels:
    {{- include "notesbase.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "notesbase.databaseURL" . | quote }}
  JWT_SECRET: {{ required "config.jwtSecret is required" .Values.config.jwtSecret | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | quote }}
  MINIO_SECRET_KEY: {{ required ".Values.minio.rootPassword is required" .Values.minio.rootPassword | quote }}
