ALTER TABLE users
  ADD COLUMN encryption_salt TEXT;

-- Populate existing users with a deterministic salt derived from their UUID.
-- New registrations get a cryptographically random salt generated by the application.
UPDATE users
SET encryption_salt = replace(id::text, '-', '');

ALTER TABLE users
  ALTER COLUMN encryption_salt SET NOT NULL;
